# Generated by Django 5.2.17 on 2026-09-24 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlendTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unloadDate', models.DateField(verbose_name='出库日')),
                ('targetCultivar', models.CharField(max_length=80, verbose_name='目标品种名')),
                ('unloadKg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='出库千克')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='开单时刻')),
                ('closedAt', models.DateTimeField(blank=True, null=True, verbose_name='结案时刻')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blend_tickets', to=settings.AUTH_USER_MODEL, verbose_name='开单人')),
            ],
            options={
                'verbose_name': '拼配下槽单',
                'verbose_name_plural': '拼配下槽单',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BlendTicketLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countedKg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='计入千克')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='gardens.blendticket', verbose_name='所属下槽单')),
                ('trough', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blend_lines', to='gardens.trough', verbose_name='槽位')),
            ],
            options={
                'verbose_name': '拼配下槽明细',
                'verbose_name_plural': '拼配下槽明细',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('ticket', 'trough'), name='uniq_trough_per_blend_ticket')],
            },
        ),
    ]
