# Generated by Django 5.2.17 on 2026-09-24 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlendUnloadTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unloadDate', models.DateField(verbose_name='出库日')),
                ('targetCultivar', models.CharField(max_length=80, verbose_name='目标品种名')),
                ('outKg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='出库千克')),
                ('openedAt', models.DateTimeField(auto_now_add=True, verbose_name='开单时刻')),
                ('closedAt', models.DateTimeField(blank=True, null=True, verbose_name='结案时刻')),
                ('openedBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blend_tickets', to=settings.AUTH_USER_MODEL, verbose_name='开单人')),
            ],
            options={
                'verbose_name': '拼配下槽单',
                'verbose_name_plural': '拼配下槽单',
                'ordering': ['-unloadDate', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BlendUnloadLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countKg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='计入千克')),
                ('trough', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blend_lines', to='gardens.trough', verbose_name='槽位')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='gardens.blendunloadticket', verbose_name='所属下槽单')),
            ],
            options={
                'verbose_name': '拼配下槽明细',
                'verbose_name_plural': '拼配下槽明细',
                'ordering': ['id'],
            },
        ),
    ]
